# Approaches to reading data
1. We should know the extension of the file e.g xls, xlsx, csv, json etc.
2. We tell where the file is located e.g
    - in the same folder with the notebook
    - in another folder/dir

In [4]:
import pandas as pd

In [5]:
#reading a csv file
student_data = pd.read_csv("StudentsPerformance.csv")
student_data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
#count of (rows,columns)
student_data.shape

(1000, 8)

In [7]:
#top five rows
student_data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [8]:
#more that top five rows
student_data.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [9]:
#bottom five rows
student_data.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [10]:
student_data.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [11]:
student_data.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [12]:
student_data.info()  #non-null means that there are no missing values in the dataset

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [13]:
#how to use "Copy path" on an external file to read an excel file
diamond = pd.read_excel("C:/Users/Desire Nabatanzi/Desktop/before test/s26B38040.xlsx")
diamond

,NAMES,OLD TESTAMENT,PROB,PROGRAMMING,SUM,AVG,RANK,COMMENT,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,ANEESA,40.0,50.0,59.0,149.0,49.666667,3.0,FAIR,NaN,NaN,NaN
1,LUKE,36.0,25.0,27.0,88.0,29.333333,5.0,FAIL,NaN,NaN,NaN
2,KC,12.0,67.0,83.0,162.0,54.000000,2.0,FAIR,NaN,NaN,NaN
3,ANAYA,80.0,94.0,45.0,219.0,73.000000,1.0,GOOD,NaN,NaN,NaN
4,TRINITY,65.0,23.0,34.0,122.0,40.666667,4.0,FAIR,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,FAIL
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,FAIR
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,GOOD
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,EXCELLENT

1. Find the mean math score.

In [14]:
student_data["math score"].mean()

np.float64(66.089)

2. What is the median reading score.

In [15]:
student_data["reading score"].median()

np.float64(70.0)

3. What is the modal writing score.

In [ ]:
student_data["writing score"].mode()[0]

0    74
Name: writing score, dtype: int64

4. Find the average math score for females.

In [17]:
student_data[student_data['gender']=='female']["math score"].mean()

np.float64(63.633204633204635)

5. Construct a new column called total(summation of math, reading and writing scores) and find its average.

In [18]:
student_data["Total"] = student_data["math score"] + student_data["reading score"] + student_data["writing score"]
student_data["Total"].mean()

np.float64(203.312)

### Measures of position
## Quartiles

In [19]:
student_data["math score"].quantile(0.25)  #lower quartile == 0.25

np.float64(57.0)

In [20]:
student_data["math score"].quantile(0.5)  #middle quartile(median) == 0.5

np.float64(66.0)

In [21]:
student_data["math score"].quantile(0.75)   #upper quartile == 0.75

np.float64(77.0)

In [22]:
#interquartile range
student_data["math score"].quantile(0.75) - student_data["math score"].quantile(0.25)

np.float64(20.0)

### PERCENTILES

In [23]:
import numpy as np

Find the 90th percentile of math score

In [24]:
ninety_per = np.percentile(student_data["math score"], 90)
ninety_per

np.float64(86.0)

In [25]:
per = np.percentile(student_data["math score"], 75)   #same as the upper quartile
per

np.float64(77.0)