In [28]:
import pandas as pd

In [29]:
titanic = pd.read_csv("titanic.csv")

In [30]:
titanic.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [31]:
data = titanic[["survived", "pclass","sex","age","alone","embark_town"]].copy()
data

     survived  pclass     sex   age  alone  embark_town
0           0       3    male  22.0  False  Southampton
1           1       1  female  38.0  False    Cherbourg
2           1       3  female  26.0   True  Southampton
3           1       1  female  35.0  False  Southampton
4           0       3    male  35.0   True  Southampton
..        ...     ...     ...   ...    ...          ...
886         0       2    male  27.0   True  Southampton
887         1       1  female  19.0   True  Southampton
888         0       3  female   NaN  False  Southampton
889         1       1    male  26.0   True    Cherbourg
890         0       3    male  32.0   True   Queenstown

[891 rows x 6 columns]

Find the number of passengers that:
    - survived
    -are male
    -travelled alone
    -travelled infirst class

In [32]:
survived= data["survived"] == 1
print(f"survived number is {survived.sum()}")

survived number is 342

In [33]:
male = data["sex"] == "male"
male = male.sum()
print(f"Male number is {male}")

Male number is 577

Find the probability of that:
    -survived

In [34]:
preferred = survived.sum()
sample_space= data.shape[0]
prob = preferred/sample_space
print(f"The probability is {prob:.4f}")

The probability is 0.3838

Alternatively

In [35]:
def prob(event):
    return event.mean()

In [36]:
survived = data["survived"] == 1
prob(survived)

np.float64(0.3838383838383838)

In [37]:
alone = data["alone"] == True
prob(alone)

np.float64(0.6026936026936027)

### Joint Events

How many passengers embarked on southhampton and travelled alone

In [38]:
embark_southhampton = data["embark_town"]== "Southampton"
alone= data["alone"] == True
joint_event = embark_southhampton & alone
joint_event.sum()

np.int64(393)

What is the probability for the above

In [39]:
prob = prob(joint_event) 
print(f"The probability is {prob:.4f}")

The probability is 0.4411

The Contingency table(Frequency Table)  #two categorical values

In [40]:
joint = pd.crosstab(data["sex"],data["survived"], normalize=True)
joint.columns = ["did not survive", "survived"]
joint

        did not survive  survived
sex
female         0.090909  0.261504
male           0.525253  0.122334

## Mutually Exclusive

In [41]:
male = data["sex"] == "male"
female = data["sex"] == "female"
union = male|female

Calculate the individual probabilities of events and the union
Make a conclusion

In [42]:
P_male = prob(male)
P_female = prob(female)
P_union = prob(union)

sum_prob = P_male + P_female

print(sum_prob)
print(P_union)  #since both sum and union are 1, the events are mutually exclusive

TypeError: 'numpy.float64' object is not callable

Using titanic, implement a scenario to check for independent events

In [ ]:
male = data["sex"] == "male"
survived = data["survived"] == 1
male_and_survived = male & survived

In [ ]:
P_male = prob(male)
P_survived = prob(survived)
P_male_and_survived = prob(male_and_survived)

In [ ]:
product = P_male * P_survived
print(product)
print(P_male_and_survived)  #since both product and P_male_and_survived are not equal, the events are not independent

0.24856874015123173
0.122334455667789

From titanic, find the probability that the passenger survived given that is male(Conditional)

In [45]:
prob_survived_given_that_is_male = P_male_and_survived / P_male
print(f"The probability is {prob_survived_given_that_is_male:.4f}")

The probability is 0.1889