In [1]:
import pandas as pd

In [2]:
titanic = pd.read_csv('titanic.csv')
titanic.head()

data = titanic[['survived', 'pclass', 'sex', 'age', 'alive', 'alone', 'embark_town', 'class']].copy()
data

     survived  pclass     sex   age alive  alone  embark_town   class
0           0       3    male  22.0    no  False  Southampton   Third
1           1       1  female  38.0   yes  False    Cherbourg   First
2           1       3  female  26.0   yes   True  Southampton   Third
3           1       1  female  35.0   yes  False  Southampton   First
4           0       3    male  35.0    no   True  Southampton   Third
..        ...     ...     ...   ...   ...    ...          ...     ...
886         0       2    male  27.0    no   True  Southampton  Second
887         1       1  female  19.0   yes   True  Southampton   First
888         0       3  female   NaN    no  False  Southampton   Third
889         1       1    male  26.0   yes   True    Cherbourg   First
890         0       3    male  32.0    no   True   Queenstown   Third

[891 rows x 8 columns]

In [3]:
survived = data['survived'] == 1
alone = data['alone'] == True
male = data['sex'] == 'male'
first = data['class'] == 'First'


alone.sum()

np.int64(537)

In [4]:
data.shape[0]

891

In [5]:
prefered = first.sum()

prob = prefered / data.shape[0]
prob

np.float64(0.24242424242424243)

In [6]:
def f(condition):
    return condition.mean()

In [7]:
f(first)

np.float64(0.24242424242424243)

In [8]:
f(alone)

np.float64(0.6026936026936027)

In [9]:
f(survived)

np.float64(0.3838383838383838)

## Joint Events
These are events that occur at the same time.\
Example:\
How many passengers embarked on southampton and travelled alone

In [10]:
embark_southampton = data['embark_town'] == 'Southampton'
alone = data['alone'] == True

joint_event = embark_southampton & alone
joint_event.sum()

np.int64(393)

what is the probability of a passenger chosen at random who embarked at southampton and travelled alone

In [11]:
prob = f(embark_southampton & alone)
print (f"The probability is {prob:.4f}")

The probability is 0.4411

#### The Contingency Table(Frequency Table)

In [12]:
joint = pd.crosstab(data['sex'], data['survived'], normalize=True)
joint.columns = ['did not survive', 'survived']
joint

        did not survive  survived
sex
female         0.090909  0.261504
male           0.525253  0.122334