# Probability and Statistics: Lab Seven
## Probability Theory
### Mutually Exclusive Events
These are events that can not occur at the same time.\
Example:
- When you toss one coin, you can not get both the Head and Tail at the same time.
- For the Titanic dataset, a passenger can not both survive and not survive.
- Suppose Event A = passenger survived and Event B = passenger did not survive.

For these two events `A` and ` B`,: 
$$ \text{Intersection:}\  \text{A} \cap \text{B} = \  \varnothing$$

therefore: $$P(\  \text{A} \cap \text{B}) = \ 0$$

Illustration of Mutually Exclusive Events using the Titanic dataset.

Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

Load the titanic dataset and display the first five rows

In [3]:
titanic = pd.read_csv('titanic.csv')

data = titanic[['survived', 'sex', 'pclass']].copy()
data.shape[0]

891

In [6]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

A contigency table of `sex` against `sex` shows that there are no passengers who are both female and male. The off-diagonal cells are zero, demonstrating that the events "Female" and "Male" are mutually exclusive.

In [3]:
joint = pd.crosstab(data['sex'],data['sex'])
joint.columns = ['female','male']
joint

        female  male
sex
female     314     0
male         0   577

`Note`: For mutually exclusive events:
$$P(\  \text{A} \cup \text{B}) = \ P(\  \text{A}) + P(\  \text{B})$$

 : The union is computed using the logical OR (`|`) operator.

Define some events i.e male and female and check whether they satisfy the condition above.

In [4]:
male = data['sex'] == 'male'
female = data['sex'] == 'female'

union = male | female

Define a function to calculate probability

In [5]:
def prob(event):
    return event.mean()

Calculate the individual probabilities of the events and that of the union.\
The printed results show that the condition for mutually exclusive events is fullfilled. Hence the two events are mutually exclusive.

In [6]:
P_male = prob(male)
P_female = prob(female)
P_union = prob(union)

sum = P_male + P_female

print(f"P(male U female) = {P_union}")
print(f"P(male) + P(female) = {sum}")

P(male U female) = 1.0
P(male) + P(female) = 1.0

Question: Implement the same using the event `Survived`

### Indepedent Events
Events A and B are independent if the occurence of one event does `not affect` the probability of the other event.\
Independent events can occur simultaneously.\
`Note`: For Indepedent events:
$$P(\  \text{A} \cap \text{B}) = \ P(\  \text{A}) . P(\  \text{B})$$

Examples:
- Event A: Tossing a coin and getting a Head.
- Event B: Rolling a die and getting a 6.\
These events are independent because tossing a coin has no effect on rolling a die.

Using the titanic dataset to check for independent events.

In [7]:
male = data['sex'] == 'male'
survived = data['survived'] == 1
m_and_s = male & survived

P_male = prob(male)
P_survived = prob(survived)
P_male_and_survived = prob(m_and_s)

P_pdt = P_male * P_survived

print(f"P(male n survived) is {P_male_and_survived:.4f}")
print(f"P(male) * P(survived) is {P_pdt:.4f}")

P(male n survived) is 0.1223
P(male) * P(survived) is 0.2486

The results above show that the events `Male` and `Survived` are  not independent since the values are not equal.

An example of events that are independent:\
Event `head` on tossing a coin and Event `4` on rolling a die are independent events.

In [8]:
coin = ['H', 'T']
die = [1, 2, 3, 4, 5, 6]
coin_die = [(c,d) for c in coin for d in die]

head = [c == 'H' for c in coin]
four = [d == 4 for d in die]
head_and_four = [(c == 'H' and d == 4) for c in coin for d in die]

To compute the probabilities, we shall use the `prob` function. But since we are now working with lists, we shall modify the function slightly so that the lists can first be converted into arrays before computing the mean.

In [9]:
def prob_1(event):
    return np.mean(event)

In [10]:
P_head = prob_1(head)
P_four = prob_1(four)
P_head_and_four = prob_1(head_and_four)

P_pdt = P_head * P_four

print(f"P_head n P_four = {P_head_and_four:.4f}")
print(f"P_head * P_four = {P_pdt:.4f}")

P_head n P_four = 0.0833
P_head * P_four = 0.0833

The results above show that the events `head` on a coin and `4` on a die are independent events since the values are equal.

### Conditional Probability
This is the probability of event `A` occuring given event `B` has already occured. It is given by: 

$$
P(A \mid B) = \frac{P(A \cap B)}{P(B)}
$$

Example: From the titanic dataset, the probability that a passenger survived given that is a male.

In [11]:
male = data['sex'] == 'male'
m_and_s = male & survived

P_male = prob(male)
P_male_and_survived = prob(m_and_s)

P_survived_given_male = P_male_and_survived / P_male
print(f"P(survived | male) = {P_survived_given_male:.4f}")

P(survived | male) = 0.1889

Question: Using the titanic dataset;
- Are the events "a passenger was in first class" and "a passenger was in third class" mutually exclusive?
- Determine whether the events "traveling in first class" and "surviving" are independent. Justify your answer.
- What is the probability that a passenger survived, given that the passenger was traveling in first class?
- If a randomly selected passenger was in third class, what is the probability that they survived?